# Generated by Django 2.1.15 on 2022-06-05 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='flowtable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('switch_id', models.CharField(max_length=32)),
                ('flow_type', models.CharField(max_length=32)),
                ('flow_id', models.IntegerField()),
                ('flow_name', models.CharField(max_length=32)),
                ('table_id', models.IntegerField()),
                ('match', models.TextField()),
                ('instructions', models.TextField()),
                ('priority', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='QoSconfigure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('src_port', models.CharField(max_length=32)),
                ('dst_port', models.CharField(max_length=32)),
                ('burst_size', models.IntegerField()),
                ('limited_rate', models.IntegerField()),
            ],
        ),
    ]
