# Generated by Django 2.1.15 on 2022-08-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qosapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
    ]
