# Generated by Django 2.1.15 on 2022-08-19 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qosapp', '0002_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
