# Generated by Django 2.1.15 on 2022-08-19 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qosapp', '0003_auto_20220819_1724'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
