# Generated by Django 2.1.15 on 2022-08-23 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qosapp', '0004_auto_20220819_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('basic', models.CharField(max_length=32)),
                ('match', models.TextField()),
                ('instructions', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='flowtable',
        ),
    ]
