# Generated by Django 2.1.15 on 2022-08-24 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qosapp', '0006_auto_20220824_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='instructions',
            field=models.TextField(null=True),
        ),
    ]
