# Generated by Django 2.1.15 on 2022-08-26 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qosapp', '0008_auto_20220826_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flow',
            old_name='statisitcs',
            new_name='statistics',
        ),
    ]
